name: Terraform Deploy

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  terraform:
    name: 'Terraform Apply'
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./terraforms

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configura Versão
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: '1.11.3'

      - name: Debug GCP_CREDENTIALS (parcial)
        run: |
          echo "Início: ${GCP_CREDENTIALS:0:60}..."
          echo "Final: ...${GCP_CREDENTIALS: -60}"
        env:
          GCP_CREDENTIALS: ${{ secrets.CREDENCIAIS_GCP }}

      - name: Carregar Credenciais
        run: |
          printf "%s" "${{ secrets.CREDENCIAIS_GCP }}" > credentials.json
          ls -lh
          pwd
          cat credentials.json

      - name: Iniciar 
        run: terraform init

      - name: Validar 
        run: terraform validate

      - name: Aplicar
        run: terraform apply -auto-approve
