name: Terraform Apply

on:
  workflow_dispatch:

jobs:
  terraform:
    name: 'Terraform Destroy'
    runs-on: ubuntu-latest

    env:
      GOOGLE_CREDENTIALS: ${{ secrets.CREDENCIAIS_GCP }}

    defaults:
      run:
        working-directory: ./terraforms

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configura Versão
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: '1.11.3'

      - name: Iniciar 
        run: terraform init

      - name: Validar 
        run: terraform validate

      - name: Destruir
        run: terraform destroy -auto-approve
